model_params = {
#     "data_dir": "/home/ec2-user/SageMaker/efs/data/open_source/wikiSQL/processed_data/", 
#     "data_dir": "/home/ec2-user/SageMaker/efs/data/open_source/spider/processed_data/",  
    "data_dir": "/home/ec2-user/SageMaker/efs/data/pilot_nl2sql_dev/0517_final_data/splits_w_corrected_query/In-Scope/sample_sizes/sampling_number_1/025/", 
    #"/home/ec2-user/SageMaker/efs/data/pilot_nl2sql_dev/0506_final_data/02_splits/main/all/",
    "output_dir" : "/home/ec2-user/SageMaker/efs/data/pilot_nl2sql_dev/0517_models/sampling_models/025_test/",
    "model_name" : "mrm8488/t5-base-finetuned-wikiSQL",
    "tokenizer_name" : "mrm8488/t5-base-finetuned-wikiSQL",
    "max_input_length" : 128,
    "max_output_length" : 750,
    "freeze_encoder" : False,
    "freeze_embeds" : False,
    "learning_rate" : 1e-3,
    "weight_decay" : 0.0,
    "adam_epsilon" : 1e-8,
    "warmup_steps" : 0,
    "train_batch_size" : 32,
    "eval_batch_size" : 32,
    "num_train_epochs" : 20,
    "gradient_accumulation_steps" : 1,
    "n_gpu" : 8,
    "resume_from_checkpoint" : True,
    "val_check_interval" : 0.8, 
    "n_train" : -1,
    "n_val" : -1,
    "n_test" : -1,
    "early_stop_callback" : True,
    "fp_16" : False,
    "opt_level" : "O1",
    "max_grad_norm" : 1.0,
    "seed" : None,
    "automatic_optimization" : True,
}

# ADDED_TOKENS = ['[ARG-DRUG]',
#                                    '[ARG-CONDITION]',
#                                    '[ARG-GENDER]',
#                                    '[ARG-RACE]',
#                                    '[ARG-ETHNICITY]',
#                                    '[ARG-STATE]',
#                                    '[ARG-AGE]',
#                                    '[ARG-TIMEDAYS]',
#                                    '[ARG-TIMEYEARS]',
#                                    '[GENDER-TEMPLATE]',
#                                    '[RACE-TEMPLATE]',
#                                    '[ETHNICITY-TEMPLATE]',
#                                    '[STATEID-TEMPLATE]',
#                                    '[CONDITION-TEMPLATE]',
#                                    '[DRUG-TEMPLATE]',
#                                    '[ARG-CONDITION]',
#                                    '[STATENAME-TEMPLATE]',
#                                    '[ARG-DRUG]',
#                                    '[ARG-DAYS]',
#                                    'YEAR',
#                                    'DATE_PART',
#                                    'ethnicity',
#                                    'DATEDIFF',
#                                    'DISTINCT',
#                                    'GREATEST',
#                                    'exposure',
#                                    'concept',
#                                    '[SCHEMA]',
#                                    'SELECT',
#                                    'gender',
#                                    'GROUP',
#                                    'LEAST',
#                                    'UNION',
#                                    'COUNT',
#                                    'WHERE',
#                                    'JOIN',
#                                    'FROM',
#                                    'drug',
#                                    'AND',
#                                    '_id',
#                                    'pe1',
#                                    'pe2',
#                                    'pe3',
#                                    'pe4',
#                                    'dr1',
#                                    'dr2',
#                                    'dr3',
#                                    'dr4',
#                                    'con1',
#                                    'con2',
#                                    'con3',
#                                    'con4',
#                                    'temp1',
#                                    'temp2',
#                                    'temp3',
#                                    'temp4',
# #                                    'eth',
# #                                    'AS',
#                                    'OR',
#                                    'BY',
# #                                    'ON',
# #                                    'dr'
#                                    ] + [f'[{i}]' for i in range(10)]


ADDED_TOKENS = ['[ARG-DRUG]',
                                   '[ARG-CONDITION]',
                                   '[ARG-GENDER]',
                                   '[ARG-RACE]',
                                   '[ARG-ETHNICITY]',
                                   '[ARG-STATE]',
                                   '[ARG-AGE]',
                                   '[ARG-TIMEDAYS]',
                                   '[ARG-TIMEYEARS]',
                                   '[GENDER-TEMPLATE]',
                                   '[RACE-TEMPLATE]',
                                   '[ETHNICITY-TEMPLATE]',
                                   '[STATEID-TEMPLATE]',
                                   '[CONDITION-TEMPLATE]',
                                   '[DRUG-TEMPLATE]',
                                   '[ARG-CONDITION]',
                                   '[STATENAME-TEMPLATE]',
                                   '[ARG-DRUG]',
                                   '[ARG-DAYS]',
                                   'DATEDIFF',
                                   'DISTINCT',
                                   'GREATEST',
                                   '[SCHEMA]',
                                   'SELECT',
                                   'GROUP',
                                   'LEAST',
                                   'UNION',
                                   'COUNT',
                                   'WHERE',
                                   'JOIN',
                                   'FROM',
                                   'AND',
                                   'AS',
                                   'OR',
                                   'BY',
                                   'ON'
                                   ] + [f'[{i}]' for i in range(10)]